name: 同步最新版日志与主页介绍
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 1 * * *" # 每天凌晨1点运行（UTC+8）
  workflow_dispatch:
    inputs:
      force_update:
        description: '是否强制更新（忽略版本检查）'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # 快速克隆

      - name: 安装依赖（解析/翻译工具）
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq translate-shell wget

      - name: 获取最新版本信息
        id: get-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          REPO="acidanthera/OpenCorePkg"
          response=$(curl -s https://api.github.com/repos/${REPO}/releases/latest)
          TAG_NAME=$(echo "$response" | jq -r '.tag_name')
          ASSETS=$(echo "$response" | jq -r '.assets[].name' | tr '\n' ',') # 资产列表转为逗号分隔
          RELEASE_NOTES=$(echo "$response" | jq -r '.body')

          # 翻译日志（失败则用原文）
          TRANSLATED_NOTES=$(echo "$RELEASE_NOTES" | trans -b -e google -t zh-CN 2>/dev/null || echo "$RELEASE_NOTES")

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "ASSETS=$ASSETS" >> $GITHUB_OUTPUT
          echo "TRANSLATED_NOTES=$TRANSLATED_NOTES" >> $GITHUB_OUTPUT

      - name: 生成主页内容
        run: |
          # 主页介绍（可自定义）
          HOMEPAGE_INTRO="# OpenCorePkg 最新版本同步\n这是一个自动同步 [OpenCorePkg](https://github.com/acidanthera/OpenCorePkg) 最新版本资产与日志的仓库。"

          # 资产部分
          ASSET_SECTION="\n### 最新版资产\n- ${ASSETS//,/\n- }" # 逗号转列表项

          # 日志部分
          LOG_SECTION="\n### 更新日志\n#### ${TAG_NAME}\n${TRANSLATED_NOTES}"

          # 合并内容
          ALL_CONTENT="$HOMEPAGE_INTRO$ASSET_SECTION$LOG_SECTION"

          # 写入或创建README.md
          if [ -f README.md ]; then
            echo "$ALL_CONTENT" > README.md # 覆盖写入（如需追加改为>>）
          else
            echo "$ALL_CONTENT" >> README.md
          fi

      - name: 提交更改
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔄 同步 ${TAG_NAME} 版本日志
          files: README.md
