name: 克隆全部分支（含权限和子模块）

on:
  workflow_dispatch:

jobs:
  clone-all:
    runs-on: ubuntu-latest
    steps:
      - name: 权限克隆仓库
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # 私有仓库需配置
          fetch-depth: 0
          submodules: recursive
          submodule-depth: 0

      - name: 拉取全部分支
        run: git fetch --all

      - name: 验证分支和文件
        run: |
          git branch -a
          ls -la app/
          echo "所有分支已克隆！"
