name: Clone Main Branch Workflow

on:
  # 触发事件：手动运行或推送代码到 main 分支
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clone-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo  # 目标仓库
          ref: main  # 克隆 main 分支
          submodules: recursive  # 递归克隆子模块（如有）

      - name: List Repository Files
        run: |
          ls -la  # 列出克隆后的文件
          echo "Repository cloned successfully!"

      - name: Validate Configuration
        # 可选：增加项目特定校验（如检查配置文件、依赖等）
        run: |
          # 示例：检查 README 文件是否存在
          if [ ! -f "README.md" ]; then
            echo "Error: README.md not found!"
            exit 1
          fi
          echo "Configuration validation passed."
