# .github/workflows/mirror-repo.yml
name: Mirror Repository

on:  # 触发配置开启
  push:  # push触发
    branches:  # 分支限制
      - main  # 仅main分支触发
  schedule:  # 定时任务配置
    - cron: "0 1 * * *"  # UTC时间1:00（北京时间9:00）
  workflow_dispatch:  # Actions标签页手动触发
    inputs:  # 输入参数配置
      force_sync:  # 参数名称
        description: 'Force immediate sync'  # 强制同步

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo
          path: source
          fetch-depth: 0  # 获取完整提交历史

      - name: Setup target repo
        run: |
          git clone --mirror https://github.com/harry0703/MoneyPrinterTurbo.git target-mirror
          cd target-mirror
          git remote set-url --push origin https://${{ secrets.TARGET_TOKEN }}@github.com/https://github.com/githurosi/YourUsername-MoneyPrinterTurbo-Mirror.git

      - name: Push to target repo
        run: |
          cd target-mirror
          git push --mirror

      - name: Cleanup
        run: |
          rm -rf source target-mirror
