name: 权限克隆仓库工作流
on:
  workflow_dispatch:  # 手动触发，可按需改为自动触发事件（如 push）

jobs:
  clone-repo-with-token:
    runs-on: ubuntu-latest
    steps:
      - name: 权限克隆仓库
        uses: actions/checkout@v4
        with:
          # 目标仓库地址（格式：用户名/仓库名）
          repository: githurosi/moneyprinter-turbo
          # 关键：使用 PAT 权限克隆（需提前配置到仓库 Secrets）
          token: ${{ secrets.TARGET_PAT }}  # 引用仓库中的 PAT 令牌
          fetch-depth: 0  # 获取所有历史记录
          submodules: recursive  # 递归克隆子模块（如有）

      - name: 验证克隆结果
        run: |
          echo "===== 仓库文件列表 ====="
          ls -la
          echo "===== 分支列表 ====="
          git branch -a  # 查看所有分支（含远程分支）
